[package]
name = "spark-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27"
egui = "0.27"
egui-file-dialog = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
winterfell = "0.12"
reqwest = { version = "0.11", features = ["blocking", "json"] }
